config/routes.rb
Rize::Application.routes.draw do
  devise_for :users, only: [:sessions, :passwords]

  root to: 'application#root'
  get '/dashboard' => 'dashboard#show', as: :dashboard

  get '/lessons'    => 'lessons#index', as: :lessons
  get '/lesson/:id' => 'lessons#show',  as: :lesson
  put '/lesson/:id' => 'lessons#update'

  get '/lessons/:lesson_id/exercises' => 'exercises#index', :as => :lesson_exercises

  get '/lessons/:lesson_id/comments' => 'comments#index', :as => :lesson_comments
  post '/lessons/:lesson_id/comments' => 'comments#create'

  get '/exercises/:exercise_id/comments' => 'comments#index', :as => :exercise_comments
  post '/exercises/:exercise_id/comments' => 'comments#create'

  get '/exams'     => 'exams#index', as: :exams
  get '/exams/:id' => 'exams#show',  as: :exam
  put '/exam/:id'  => 'exams#update'

   get '/klasses/:klass_id/lessons' => 'lessons#index', :as => :students

end

app/models/lesson.rb
# encoding: utf-8
class Lesson < ActiveRecord::Base
  # Accessible attributes
  attr_accessible :topic, :klass, :student, :semester, :evaluation

  # Associations
  has_one    :exam
  has_many   :exercises
  belongs_to :student, class_name: 'User'
  belongs_to :semester
  belongs_to :topic
  belongs_to :klass
  belongs_to :repeated

  # Student Id
  validates :student_id,
    presence: true,
    numericality: true

  # Semester Id
  validates :semester_id,
    presence: true,
    numericality: true

  # Topic Id
  validates :topic_id,
    presence: true,
    numericality: true

  # Klass Id
  validates :klass_id,
    presence: true,
    numericality: true

  # Evaluation
  validates :evaluation,
    length: {maximum: 10.kilobytes}

  # Grade
  validates :grade,
    allow_blank: true,
    numericality: true

  def to_s
    "#{topic.name}"
  end
end

app/controllers/lessons_controller.rb
# encoding: utf-8
class LessonsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @lessons = Lesson.all
    return index_teacher if current_user.role? :evaluator
    return index_student if current_user.role? :student
  end

  def show
    @lesson = Lesson.find params[:id]
  end

  def update
    @lesson = Lesson.find params[:id]

    Lesson.transaction do
      if params[:lesson] and params[:lesson][:grade]
        @lesson.grade = params[:lesson][:grade]
      elsif params[:finalize] == "true" and @lesson.grade
        @lesson.finalized_at = Time.now.utc
      end

      @lesson.save!
    end

    redirect_to students_path(@lesson)
  end

  private
  def index_teacher
    render 'index_teacher'
  end

  def index_student
    render 'index_student'
  end
end

app/views/lessons/_grade.html.haml
- lesson ||= @lesson

Mérés jegy
= form_for lesson do |f|
  - (1..5).each do |g|
    #{g}
    = f.radio_button :grade, g

  - if lesson.finalized_at
    = f.submit 'Mentés', disabled: true
  - else
    = f.submit 'Mentés'

app/views/lessons/index_student.html.haml
%h1 Mérések

%table.table.table-striped
  - @lessons.each do |lesson|
    %tr{'data-lesson-id' => "#{lesson.id}"}
      %td= lesson
      %td="Mérés jegy: #{lesson.grade if lesson.finalized_at}"
      %td= "Beugró jegy: #{lesson.exam.grade if lesson.exam and lesson.exam.finalized_at}"
      %td= "Jegyzőkönyv jegy: #{lesson.exercises.last.grade if lesson.exercises.last and lesson.exercises.last.finalized_at}"
      %td= link_to 'Jegyzőkönyv', lesson_exercises_path(lesson.id)
      %td= link_to 'Megjegyzések', lesson_comments_path(lesson.id)

app/views/lessons/index_teacher.html.haml
%h1 Hallgatók

%table.table.table-striped
  - @lessons.each do |lesson|
    %tr{'data-student-id' => "#{lesson.id}"}
      %td #{lesson.student.name}
      %td= link_to 'Jegyzőkönyv letöltése', '#'
      %td= link_to 'Megjegyzések', lesson_comments_path(lesson.id)

      - if lesson.exam
        %td= render :partial => 'lessons/grade', :locals => {:lesson => lesson}
        %td= button_to 'Véglegesítés', lesson_path(lesson, :finalize => true), :method => :put if lesson.finalized_at.nil?

        %td= render :partial => 'exams/grade', :locals => {:exam => lesson.exam}
        %td= button_to 'Véglegesítés', exam_path(lesson.exam, :finalize => true), :method => :put if lesson.exam.finalized_at.nil?