config/routes.rb
Rize::Application.routes.draw do
  devise_for :users, only: [:sessions, :passwords]

  root to: 'application#root'
  get '/dashboard' => 'dashboard#show', as: :dashboard

  get '/lessons'    => 'lessons#index', as: :lessons
  get '/lesson/:id' => 'lessons#show',  as: :lesson
  put '/lesson/:id' => 'lessons#update'

  get '/lessons/:lesson_id/exercises' => 'exercises#index', :as => :lesson_exercises

  get '/lessons/:lesson_id/comments' => 'comments#index', :as => :lesson_comments
  post '/lessons/:lesson_id/comments' => 'comments#create'

  get '/exercises/:exercise_id/comments' => 'comments#index', :as => :exercise_comments
  post '/exercises/:exercise_id/comments' => 'comments#create'

  get '/exams'     => 'exams#index', as: :exams
  get '/exams/:id' => 'exams#show',  as: :exam
  put '/exam/:id'  => 'exams#update'

   get '/klasses/:klass_id/lessons' => 'lessons#index', :as => :students

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rize</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= render template: 'layouts/menu' %>
<% end %>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/menu.html.haml
.navbar
  .navbar-inner
    %a.brand{:href => root_path} Rize
    %ul.nav
      %li.active
        = link_to 'Mérések', lessons_path
      %li
        %a{:href => "#"} Hírek
    .right.role
      #{current_user.roles.first.name}
    .btn-group.right
      %a.btn.dropdown-toggle{ "data-toggle" => "dropdown" }
        #{current_user.email}
        %span.caret
      %ul.dropdown-menu
        %li
          %a Reset password
          %a Resend confirmation e-mail
          = link_to 'Logout', destroy_user_session_path, method: 'delete'